version: '3'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:example@postgres:5432/wingvision?schema=public
    restart: unless-stopped

  rtmp:
    build:
      context: ./rtmp
      dockerfile: Dockerfile
    ports:
      - "1935:1935"
      - "7001:7001"
      - "7002:7002"
    restart: unless-stopped

  postgres:
    image: postgres:15.2-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=wingvision
    restart: unless-stopped

  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "9000:80"
    volumes:
      - ./nginx/web.conf:/etc/nginx/conf.d/default.conf:ro

  nginx:
    image: nginx:1.23.4-alpine
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
      - ./recognizer/videos:/videos/cdn/videos/:ro